/*!
 * @file    XiosWrite_test.cpp
 * @author  Joe Wallwork <jw2423@cam.ac.uk>
 * @date    19 Nov 2024
 * @brief   Tests for XIOS write method
 * @details
 * This test is designed to test the write method of the C++ interface
 * for XIOS.
 *
 */
#include <doctest/extensions/doctest_mpi.h>
#undef INFO

#include "StructureModule/include/ParametricGrid.hpp"
#include "include/Configurator.hpp"
#include "include/NextsimModule.hpp"
#include "include/ParaGridIO.hpp"
#include "include/Xios.hpp"

#include <filesystem>

namespace Nextsim {

/*!
 * Set up the XIOS handler class for testing file writing.
 *
 * The function assumes two MPI ranks.
 *
 * @param dim The number of spatial dimensions
 * @return Appropriately configured Xios handler class instance
 */
Xios setupXiosHandler(int dim)
{
    if ((dim != 2) && (dim != 3)) {
        throw std::invalid_argument("Test only implemented for 2D and 3D cases");
    }

    // Create ParametricGrid and ParaGridIO instances
    Module::setImplementation<IStructure>("Nextsim::ParametricGrid");
    ParametricGrid grid;
    ParaGridIO* pio = new ParaGridIO(grid);
    grid.setIO(pio);

    // Initialize an Xios instance called xios_handler
    // TODO: Create XIOS handler along with ParaGridIO instance
    Xios xios_handler((boost::format("context_%1$dD") % dim).str());
    REQUIRE(xios_handler.isInitialized());
    const size_t size = xios_handler.getClientMPISize();
    REQUIRE(size == 2);
    const size_t rank = xios_handler.getClientMPIRank();

    // Calendar setup
    xios_handler.setCalendarOrigin(TimePoint("2020-01-23T00:08:15Z"));
    xios_handler.setCalendarStart(TimePoint("2023-03-17T17:11:00Z"));
    Duration timestep("P0-0T01:30:00");
    xios_handler.setCalendarTimestep(timestep);

    // Set ModelArray dimensions
    const size_t nx_glo = 4;
    const size_t ny_glo = 2;
    const size_t nx = 2;
    const size_t ny = 2;
    ModelArray::setDimension(ModelArray::Dimension::X, nx_glo, nx, 0);
    ModelArray::setDimension(ModelArray::Dimension::Y, ny_glo, ny, 0);
    if (dim == 3) {
        const size_t nz = 2;
        ModelArray::setDimension(ModelArray::Dimension::Z, nz, nz, 0);
    }

    // Create a 4x2 horizontal domain with a partition halving the x-extent
    // TODO: Set local and global domain sizes upon calling ModelArray::setDimension for X and Y
    xios_handler.createDomain("xy_domain");
    xios_handler.setDomainType("xy_domain", "rectilinear");
    xios_handler.setDomainGlobalXSize("xy_domain", nx_glo);
    xios_handler.setDomainGlobalYSize("xy_domain", ny_glo);
    xios_handler.setDomainLocalXStart("xy_domain", 2 * rank);
    xios_handler.setDomainLocalYStart("xy_domain", 0);
    xios_handler.setDomainLocalXValues("xy_domain", { -1.0 + rank, -0.5 + rank });
    xios_handler.setDomainLocalYValues("xy_domain", { -1.0, 1.0 });

    if (dim == 3) {
        // Create a vertical axis with 2 points
        // TODO: Set axis size upon calling ModelArray::setDimension for Z
        xios_handler.createAxis("z_axis");
        xios_handler.setAxisValues("z_axis", { 0.0, 1.0 });
    }

    // Create fields on the two grids
    // TODO: Create field along with HField
    // NOTE: The grid should be auto-generated by the Xios handler class
    const std::string fieldId = (boost::format("field_%1$1dD") % dim).str();
    xios_handler.createField(fieldId);
    xios_handler.setFieldOperation(fieldId, "instant");
    xios_handler.setFieldGridRef(fieldId, (boost::format("grid_%1$1dD") % dim).str());
    xios_handler.setFieldReadAccess(fieldId, false);

    // Create an output file to hold data from both fields
    xios_handler.createFile("xios_test_output");
    xios_handler.setFileType("xios_test_output", "one_file");
    xios_handler.setFileOutputFreq("xios_test_output", timestep);
    xios_handler.setFileSplitFreq("xios_test_output", Duration("P0-0T03:00:00"));
    xios_handler.setFileMode("xios_test_output", "write");
    xios_handler.fileAddField("xios_test_output", fieldId);

    xios_handler.close_context_definition();
    return xios_handler;
}

/*!
 * Test file writing for the Xios handler configuration in setupXiosHandler.
 *
 * @param xios_handler Pointer to Xios handler class instance configured using setupXiosHandler
 * @param field_A Reference to nextSIM-DG HField instance to test writing to file
 */
void testFileWrite(Xios* xios_handler, HField& field_A, const std::string fieldId)
{
    // Verify calendar step is starting from zero
    REQUIRE(xios_handler->getCalendarStep() == 0);

    // Check a file with the expected name doesn't exist yet
    REQUIRE_FALSE(std::filesystem::exists("xios_test_output*.nc"));

    // Simulate 4 iterations (timesteps)
    for (int ts = 1; ts <= 4; ts++) {
        // Update the current timestep
        xios_handler->updateCalendar(ts);
        // Send data to XIOS to be written to disk
        xios_handler->write(fieldId, field_A);
        // Verify timestep
        REQUIRE(xios_handler->getCalendarStep() == ts);
    }

    // Check the files have indeed been created then remove it
    REQUIRE(std::filesystem::exists("xios_test_output_20230317171100-20230317201059.nc"));
    REQUIRE(std::filesystem::exists("xios_test_output_20230317201100-20230317231059.nc"));
    if (xios_handler->getClientMPIRank() == 0) {
        std::filesystem::remove("xios_test_output_20230317171100-20230317201059.nc");
        std::filesystem::remove("xios_test_output_20230317201100-20230317231059.nc");
    }

    xios_handler->context_finalize();
}

/*!
 * TestXiosWrite_2D
 *
 * This function tests the file writing functionality of the C++ interface for XIOS for fields with
 * two spatial dimensions. The test runs with two MPI ranks.
 */
MPI_TEST_CASE("TestXiosWrite_2D", 2)
{
    Xios xios_handler = setupXiosHandler(2);

    // Create some fake data to test writing methods
    HField field_2D(ModelArray::Type::H);
    field_2D.resize();
    const size_t nx = xios_handler.getDomainLocalXSize("xy_domain");
    const size_t ny = xios_handler.getDomainLocalYSize("xy_domain");
    for (size_t j = 0; j < ny; ++j) {
        for (size_t i = 0; i < nx; ++i) {
            field_2D(i, j) = 1.0 * (i + nx * j);
        }
    }

    testFileWrite(&xios_handler, field_2D, "field_2D");
}

/*!
 * TestXiosWrite_3D
 *
 * This function tests the file writing functionality of the C++ interface for XIOS for fields with
 * three spatial dimensions. The test runs with two MPI ranks.
 */
MPI_TEST_CASE("TestXiosWrite_3D", 2)
{
    Xios xios_handler = setupXiosHandler(3);

    // Create some fake data to test writing methods
    HField field_3D(ModelArray::Type::Z);
    field_3D.resize();
    const size_t nx = xios_handler.getDomainLocalXSize("xy_domain");
    const size_t ny = xios_handler.getDomainLocalYSize("xy_domain");
    const size_t nz = xios_handler.getAxisSize("z_axis");
    for (size_t k = 0; k < nz; ++k) {
        for (size_t j = 0; j < ny; ++j) {
            for (size_t i = 0; i < nx; ++i) {
                field_3D(i, j, k) = 1.0 * (i + nx * (j + ny * k));
            }
        }
    }

    testFileWrite(&xios_handler, field_3D, "field_3D");
}

// TODO: Consider adding a 4D test case

}
