name: Check formatting

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  clang-formatter:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: clang-format
      run: |
        sudo apt update
        sudo apt install clang-format
        for component in core dynamics physics
        do
          cd $component/src
          clang-format --dry-run -Werror *cpp include/*hpp
          cd -
        done

  cmake-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clang-format
      run: |
        pip install cmakelang
        cmake-lint $(find . -name CMakeLists.txt) --disabled {C0103,C0113}
        # NOTE: We ignore C0103, which would enforce that variables are all-caps
        # NOTE: We ignore C0113, which would enforce that comments are used
